apiVersion: v1
kind: Service
metadata:
  name: gcp-monitoring-service
spec:
  selector:
    app: gcp-monitoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
